#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import json
import sys
import agent

data = json.load(sys.stdin)

# Setup default values
ldap_admin_users = data.get("ldap_admin_users", "") # semicolon (;) list separated
ldap_domain = data.get("ldap_domain", "")
lam_login_method = data.get("lam_login_method", "list") # list or search
# bind user to the domain
if ldap_domain:
    agent.bind_user_domains([ldap_domain])
else:
    agent.bind_user_domains([])

# Setup LDAP domain
agent.set_env("LDAP_DOMAIN", ldap_domain)
# Setup LAM user
agent.set_env("LDAP_ADMIN_USERS", ldap_admin_users)
# Setup LAM login metho
agent.set_env("LAM_LOGIN_METHOD", lam_login_method)
