#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Read Lam configuration
#

import os
import sys
import json
import agent
from agent.ldapproxy import Ldapproxy

# Prepare return variable
config = {}

config["host"] =  os.environ.get("TRAEFIK_HOST")
config["http2https"] =  os.environ.get("TRAEFIK_HTTP2HTTPS") == "True"
config["lets_encrypt"] =  os.environ.get("TRAEFIK_LETS_ENCRYPT") == "True"
# retrieve LDAP domains list
lp = Ldapproxy()
domains = []
for key in lp.get_domains_list():
    domains.append({
        "name": key,
        "label": key,
        "value": key,
    })

config['ldap_domain_list'] = domains
config['ldap_domain'] = os.environ.get("LDAP_DOMAIN",'')
config['ldap_admin_users'] = os.environ.get("LDAP_ADMIN_USERS",'administrator')
# Dump the configuratio to stdou
json.dump(config, fp=sys.stdout)
