#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent

request = json.load(sys.stdin)

original_environment = request['environment']

for evar in [
        "TRAEFIK_HOST",
        "TRAEFIK_HTTP2HTTPS",
        "TRAEFIK_LETS_ENCRYPT",
        "LDAP_ADMIN_USERS",
        "LAM_LOGIN_METHOD",
        "LAM_PASSWORD",
        "LDAP_DOMAIN",
        "LAM_LICENSE"
    ]:
    agent.set_env(evar, original_environment[evar])

agent.dump_env()
